using System.Collections.Generic;
using UnityEngine;
using TMPro;
using System.Collections;

public class MixChecker1 : MonoBehaviour
{
    public TMP_InputField[] inputFields;
    public Auto1 auto1;
    public string[] correctTextAnswers;
    public int[] autoTextDependentIndices;
    public PuzzleSlot[] puzzleSlots;
    public TMP_Dropdown[] dropdowns;
    public int[] correctDropdownIndexes;
    public GameObject successMessage;
    public GameObject failureMessage;
    public ACorrect Right;
    public Ncorrect Wrong;

    // For Visual aspect
    public RandomSpawn randomSpawn;
    public Transform pointA;
    public Vector3 finalScale = new Vector3(1f, 1f, 1f);

    public float moveSpeed = 3f;



    public void CheckAllAnswers()
    {
        Debug.Log("Checking all answers...");

        bool allCorrect = true;

        string[] autoGeneratedAnswers = new string[]
        {
            auto1.SkillLevel1.text
        };

        // text input
        for (int i = 0; i < inputFields.Length; i++)
        {
            string userInput = inputFields[i].text.Trim(); //no space
            string correctAnswer;

            // Auto
            if (System.Array.Exists(autoTextDependentIndices, index => index == i))
            {
                correctAnswer = autoGeneratedAnswers[i];
                correctTextAnswers[i] = autoGeneratedAnswers[i];
            }
            else
            {
                correctAnswer = correctTextAnswers[i];
            }

            if (userInput != correctAnswer)
            {
                allCorrect = false;

            }
        }

        //Puzzle
        for (int i = 0; i < puzzleSlots.Length; i++)
        {
            if (!puzzleSlots[i].IsCorrect())
            {
                allCorrect = false;
                string incorrectPiece = puzzleSlots[i].currentPiece ? puzzleSlots[i].currentPiece.pieceIndex.ToString() : "None";

            }
        }

        // dropdown
        for (int i = 0; i < dropdowns.Length; i++)
        {
            if (dropdowns[i].value != correctDropdownIndexes[i])
            {
                allCorrect = false;

            }
        }

        // feedback
        if (allCorrect)
        {
            Right.CorrectAnimation();
            successMessage.SetActive(true);
            failureMessage.SetActive(false);
            StartCoroutine(MovePrefabsAndDestroy());

            //Debug.Log("All answers are correct.");
        }
        else
        {
            Wrong.WrongAnimation();
            successMessage.SetActive(false);
            failureMessage.SetActive(true);

            //Debug.Log("Some answers are incorrect:");

        }
    }
    IEnumerator MovePrefabsAndDestroy()
    {
        List<GameObject> spawnedPrefabs = randomSpawn.GetSpawnedPrefabs();

        // Pick a random prefab to leave behind
        GameObject prefabToLeave = spawnedPrefabs[Random.Range(0, spawnedPrefabs.Count)];

        foreach (var prefab in spawnedPrefabs)
        {
            // Skip the prefab that we want to leave
            if (prefab == prefabToLeave)
            {
                continue;
            }


            Transform randomEndPoint = randomSpawn.endPoints[Random.Range(0, randomSpawn.endPoints.Length)];

            // Move the prefab towards the end point
            while (Vector3.Distance(prefab.transform.position, randomEndPoint.position) > 0.1f)
            {
                prefab.transform.position = Vector3.MoveTowards(prefab.transform.position, randomEndPoint.position, moveSpeed * Time.deltaTime);
                yield return null;
            }

            prefab.transform.position = randomEndPoint.position;
            Destroy(prefab);
        }
        MoveAndRescaleLastPrefab(prefabToLeave);
    }
    private void MoveAndRescaleLastPrefab(GameObject prefab)
    {
        if (pointA == null)
        {
            Debug.LogError("Point A is not assigned in the Inspector!");
            return;
        }

        StartCoroutine(MoveToPointAAndRescale(prefab));
    }

    IEnumerator MoveToPointAAndRescale(GameObject prefab)
    {
        while (Vector3.Distance(prefab.transform.position, pointA.position) > 0.1f)
        {
            prefab.transform.position = Vector3.MoveTowards(prefab.transform.position, pointA.position, moveSpeed * Time.deltaTime);
            yield return null;
        }

        prefab.transform.localScale = finalScale;
    }
}
